name: GitHub Metrics

on:

  schedule:
    - cron: "0 0 * * *"
  # Manuel çalıştırma
  workflow_dispatch:

  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate GitHub Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: kerem-apaydin
          template: classic
          config_timezone: Europe/Istanbul
          base: header, activity, community, repositories, metadata

          # Dil istatistikleri
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_limit: 4


          plugin_activity: yes

  
          plugin_stars: yes


          plugin_followup: yes
